apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml
  labels:
    app: ml
spec:
  selector:
    matchLabels:
      app: ml
  template:
    metadata:
      labels:
        app: ml
    spec:
      containers:
      - name: ml
        image: codait/max-image-resolution-enhancer
        ports:
        - containerPort: 5000
